import Icon from '/imports/ui/components/common/icon/icon-ts/component';
import './Icon.css';

// More on how to set up stories at: https://storybook.js.org/docs/writing-stories#default-export
export default {
  title: 'Common/Icon',
  component: Icon,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  argTypes: {
    iconName: {
      options: [
        'screenshare-fullscreen',
        'screenshare-close-fullscreen',
        'alert',
        'mute',
        'unmute',
        'file',
        'upload',
        'fullscreen',
        'exit_fullscreen',
        'settings',
        'fit_to_screen',
        'line_tool',
        'circle_tool',
        'triangle_tool',
        'rectangle_tool',
        'text_tool',
        'plus',
        'fit_to_width',
        'undo',
        'pen_tool',
        'lock',
        'polling',
        'desktop',
        'logout',
        'video',
        'elipsis',
        'more',
        'promote',
        'application',
        'video_off',
        'user',
        'up_arrow',
        'right_arrow',
        'presentation',
        'listen',
        'left_arrow',
        'group_chat',
        'close',
        'clear_status',
        'circle',
        'substract',
        'circle_close',
        'add',
        'check',
        'chat',
        'audio_on',
        'audio_off',
        'volume_down',
        'volume_down',
        'volume_off',
        'volume_up',
        'volume_level_1',
        'volume_level_2',
        'volume_level_3',
        'no_audio',
        'time',
        'hand',
        'happy',
        'send',
        'about',
        'delete',
        'unmute_filled',
        'mute_filled',
        'listen_filled',
        'template_upload',
        'template_download',
        'download',
        'multi_whiteboard',
        'whiteboard',
        'rooms',
        'unlock',
        'record',
        'network',
        'redo',
        'thumbs_down_filled',
        'thumbs_up',
        'thumbs_up_filled',
        'checkmark',
        'speak_louder',
        'help',
        'refresh',
        'copy',
        'shortcuts',
        'warning',
        'pointer',
        'star_filled',
        'desktop_off',
        'minus',
        'download-off',
        'popout_window',
        'closed_caption',
        'alert',
        'palm_rejection',
        'no_palm_rejection',
        'device_list_selector',
        'presentation_off',
        'external-video',
        'external-video_off',
        'pin-video_on',
        'pin-video_off',
        'closed_caption_stop',
        'link',
        'manage_layout',
      ],
      control: { type: 'select' },
    },
    prependIconName: {
      control: {
        type: 'text',
      },
    },
    rotate: {
      control: {
        type: 'boolean',
      },
    },
    className: {
      control: {
        type: 'text',
      },
    },
  },
};

export const Default = {
  args: {
    iconName: '',
  },
};
