table:
  name: user_localSettings
  schema: public
select_permissions:
  - role: bbb_client
    permission:
      columns:
        - settingsJson
        - userId
      filter:
        _and:
          - meetingId:
              _eq: X-Hasura-MeetingId
          - userId:
              _eq: X-Hasura-UserId
update_permissions:
  - role: bbb_client
    permission:
      columns:
        - settingsJson
      filter:
        _and:
          - meetingId:
              _eq: X-Hasura-MeetingId
          - userId:
              _eq: X-Hasura-UserId
      check: {}
      set:
        meetingId: x-hasura-MeetingId
        userId: x-hasura-UserId
